version: 2
jobs:
  build:
    docker:
      - image: alpine 
    steps:
      - checkout
      - run: echo build
  test:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: echo test
  package:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: echo package
  publish:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: echo publish
  deploy:
    docker:
      - image: alpine 
    steps:
      - checkout
      - run: echo deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - package:
          requires:
            - test
      - publish:
          requires:
            - package
      - deploy:
          requires:
            - publish
